"""project adjustment

Revision ID: 2cd46d0294b4
Revises: f38b443bd90f
Create Date: 2024-01-15 14:04:20.759546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd46d0294b4'
down_revision = 'f38b443bd90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('uq_projects_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_projects_title'), ['title'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_projects_title'), type_='unique')
        batch_op.create_unique_constraint('uq_projects_name', ['name'])
        batch_op.drop_column('completed_at')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
