"""all models v1

Revision ID: 90c48730fcae
Revises: 56181272e29f
Create Date: 2024-01-02 09:54:01.935297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c48730fcae'
down_revision = '56181272e29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('full', sa.String(), nullable=False),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_assessment_questions'))
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('name', name=op.f('uq_projects_name'))
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('assessment', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('impact_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_table('energy_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('lighting_type', sa.String(), nullable=True),
    sa.Column('light_habits', sa.String(), nullable=True),
    sa.Column('daylighting', sa.String(), nullable=True),
    sa.Column('landscape_lights', sa.Boolean(), nullable=True),
    sa.Column('heating_type', sa.String(), nullable=True),
    sa.Column('heating_age', sa.Integer(), nullable=True),
    sa.Column('cooling_type', sa.String(), nullable=True),
    sa.Column('cooling_age', sa.Integer(), nullable=True),
    sa.Column('deg_between_setpoints', sa.Integer(), nullable=True),
    sa.Column('filter_changes', sa.Boolean(), nullable=True),
    sa.Column('ductwork_condition', sa.Integer(), nullable=True),
    sa.Column('air_sealing', sa.Integer(), nullable=True),
    sa.Column('roof_color', sa.String(), nullable=True),
    sa.Column('window_age', sa.Integer(), nullable=True),
    sa.Column('window_type', sa.String(), nullable=True),
    sa.Column('e_star_appliances', sa.Integer(), nullable=True),
    sa.Column('toilet_flush', sa.Float(), nullable=True),
    sa.Column('sink_flow', sa.Float(), nullable=True),
    sa.Column('shower_flow', sa.Float(), nullable=True),
    sa.Column('water_heater_type', sa.String(), nullable=True),
    sa.Column('water_heater_age', sa.Integer(), nullable=True),
    sa.Column('rainwater', sa.Boolean(), nullable=True),
    sa.Column('irrigation', sa.String(), nullable=True),
    sa.Column('irrigation_controls', sa.String(), nullable=True),
    sa.Column('re_sources', sa.String(), nullable=True),
    sa.Column('re_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_energy_assessments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_assessments'))
    )
    op.create_table('project_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_updates_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_updates'))
    )
    op.create_table('user_recommendations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_user_recommendations_recommendation_id_recommendations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_recommendations_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'recommendation_id', name=op.f('pk_user_recommendations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recommendations')
    op.drop_table('project_updates')
    op.drop_table('energy_assessments')
    op.drop_table('recommendations')
    op.drop_table('projects')
    op.drop_table('energy_assessment_questions')
    # ### end Alembic commands ###
