"""add title to Recommendation

Revision ID: c0038cccd54f
Revises: edf1e48feffb
Create Date: 2024-01-12 13:04:34.507518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0038cccd54f'
down_revision = 'edf1e48feffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_assessments', schema=None) as batch_op:
        batch_op.alter_column('landscape_lights',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('filter_changes',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('grounds',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('rainwater',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('energy_assessments', schema=None) as batch_op:
        batch_op.alter_column('rainwater',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('grounds',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('filter_changes',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('landscape_lights',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
