"""add triggering values to Recommendations

Revision ID: edf1e48feffb
Revises: 78f589dbe61d
Create Date: 2024-01-12 12:16:36.464640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf1e48feffb'
down_revision = '78f589dbe61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggering_values', sa.ARRAY(sa.String()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('triggering_values')

    # ### end Alembic commands ###
