"""swapped out more ints for strings

Revision ID: f38b443bd90f
Revises: c0038cccd54f
Create Date: 2024-01-12 13:55:37.760610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38b443bd90f'
down_revision = 'c0038cccd54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_assessments', schema=None) as batch_op:
        batch_op.alter_column('ductwork_condition',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('e_star_appliances',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_assessments', schema=None) as batch_op:
        batch_op.alter_column('e_star_appliances',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ductwork_condition',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
