"""assessment changes

Revision ID: 08f13765184e
Revises: f5bba40fa88d
Create Date: 2024-01-11 17:00:54.504114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f13765184e'
down_revision = 'f5bba40fa88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grounds', sa.Boolean(), nullable=True))
        batch_op.drop_column('air_sealing')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_sealing', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('grounds')

    # ### end Alembic commands ###
