"""relate questions and recommendations

Revision ID: ad195ff9b503
Revises: 751846d2ab95
Create Date: 2024-01-07 14:38:03.938678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad195ff9b503'
down_revision = '751846d2ab95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_assessment_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_recommendations_question_id_energy_assessment_questions'), 'energy_assessment_questions', ['question_id'], ['id'])
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_recommendations_question_id_energy_assessment_questions'), type_='foreignkey')
        batch_op.drop_column('question_id')

    with op.batch_alter_table('energy_assessment_questions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
