"""add cat and image to project

Revision ID: c0e1d6cd1999
Revises: 3fa3b32a5938
Create Date: 2024-01-18 11:50:16.426573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e1d6cd1999'
down_revision = '3fa3b32a5938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
